### ISSUE TITLE
FTPS isn't working

### ISSUE THREAD

**Issue by maicol07** [luandersonn/MyFTP#23]
Error setting port to 443:

![](https://user-images.githubusercontent.com/9463142/131216357-d9b30568-a016-428f-b58f-1da610f7c090.png)

Error setting port to 21:

![](https://user-images.githubusercontent.com/9463142/131216365-edca3753-22ec-4a5a-862f-1840cae1827b.png)

**Comment by luandersonn** [comment]
Thank you @maicol07, right now, we're supporting only ftp.
