### ISSUE TITLE
Multi language option

### ISSUE THREAD

**Issue by opastorello** [luandersonn/MyFTP#24]
Multi language option depending on operating system language or user choice.

PS: I really liked the software and its ease, it became my day-to-day FTP client.

**Comment by luandersonn** [comment]
Thanks @opastorello, we're already working on multi-language support.

**Comment by luandersonn** [comment]
@opastorello PT-BR?

**Comment by opastorello** [comment]
> @opastorello PT-BR?

Correto PT-BR

**Comment by luandersonn** [comment]
Se houver algum erro na tradução, só avisar
