### ISSUE TITLE
Class library cannot be started directly

### ISSUE THREAD

**Issue by x118056** [luandersonn/MyFTP#37]
I'm new to this so I don't know how to correctly run this, can you help me?
![image_2022-05-10_075823367](https://user-images.githubusercontent.com/47490455/167521753-9d7d8d67-e3ac-407a-aa59-27e91d89d000.png)

**Comment by luandersonn** [comment]
Can you share a screenshot from project on VS?

**Comment by x118056** [comment]
Here
![image_2022-05-10_080346084](https://user-images.githubusercontent.com/47490455/167522185-73cb1f5d-6d52-44dd-9d1b-9588597fe45c.png)

**Comment by luandersonn** [comment]
This is not MyFTP, but the FluentFTP library


________________________________
De: x118056 ***@***.***>
Enviado: segunda-feira, 9 de maio de 2022 22:04
Para: luandersonn/MyFTP ***@***.***>
Cc: Luandersonn Airton ***@***.***>; Comment ***@***.***>
Assunto: Re: [luandersonn/MyFTP] Class library cannot be started directly (Issue #37)


Here
[image_2022-05-10_080346084]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F47490455%2F167522185-73cb1f5d-6d52-44dd-9d1b-9588597fe45c.png&data=05%7C01%7C%7Cd1a37a86467e4f5bbc0508da3220f97e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637877414460699816%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mfoSgZDoLZLse8gG5sQIc%2FNotKJ%2BdziCSwcKbeUAbAs%3D&reserved=0>
