### ISSUE TITLE
Double-clicking element often do not work

### ISSUE THREAD

**Issue by JensMertelmeyer** [luandersonn/MyFTP#5]
Double-clicking elements (downloading & opening a file or navigating into a folder) often does not work. I cannot really reproduce when it does, and when it does not - It appears to be random.

I have a feeling that with folders, it has a higher chance when you click the symbol instead of the text..

Version number: Unknown. Downloaded it from the store, version number not shown anywhere.

**Comment by JensMertelmeyer** [comment]
I have updated to version `2021.805.2229.0` and it seems that for *folders*, you have to click the tiny little gap here:
![image](https://user-images.githubusercontent.com/1827784/128472763-536df597-fd01-4e8a-857b-3e252cd412ea.png)

Watch this:

https://user-images.githubusercontent.com/1827784/128472813-b819ee03-c4b2-4a68-8fa2-e21b562e043c.mp4

**Comment by luandersonn** [comment]
Are you still experiencing this bug?

**Comment by JensMertelmeyer** [comment]
App version "2021.816.2108.0 (Preview)" seems to be fine now 😊
