### ISSUE TITLE
Is this ARM Native?

### ISSUE THREAD

**Issue by ghost** [luandersonn/MyFTP#53]
Hi I am looking around for a more modern FTP / SCP Client and stumbled upon yours. I just bought a new ASUS Vivobook (**Qualcomm X Elite ARM chip**) in it and am trying to find some app that is better than FileZilla but also modern and works with Windows 11 ARM. 

It wasn't quite apparent so asking as it seems to be only x86 & x64 (meaning Intel and AMD only). 

Also are you still working on this project or are there no new features after the initial release in August 2021?

**Comment by luandersonn** [comment]
@kannexca MyFTP is ARM compatible.

I've been working on an update. But I've been very busy with work over the last few years, so I haven't been able to finish it. But I'm confident that I'll be working on this app again in 2025. See the progress in issue #45
