### ISSUE TITLE
Feature request: Go back/upwards with hotkey

### ISSUE THREAD

**Issue by JensMertelmeyer** [luandersonn/MyFTP#6]
Implement shortcuts like in Windows explorer:

- `Backspace` for _One directory up_
- `Alt + Left` for _Go back_
- `Mouse back` for _Go back_

**Comment by luandersonn** [comment]
Thank you! Your suggestion has been implemented in #10  (plus `Alt + Right` and `Mouse Forward` for _Go Forward_)

More feedbacks are welcome
