### ISSUE TITLE
Column Layout not scaling correctly

### ISSUE THREAD

**Issue by JensMertelmeyer** [luandersonn/MyFTP#7]
I suppose the list of files should behave like the column headers above them

https://user-images.githubusercontent.com/1827784/128305287-a5dc7529-205c-4562-bdca-9990f87929ca.mp4

**Comment by luandersonn** [comment]
It appears that in Windows 10 the ListView does not stretch to ListViewItem automatically (Windows 11 does). Thanks for reporting this :)

**Comment by luandersonn** [comment]
Apparently, in Windows 10, the ListView does not stretch the ListViewItem automatically (Windows 11 does). Thanks for reporting this :)

**Comment by luandersonn** [comment]
Please check if it has been fixed in version 2021.805.1758.0

**Comment by JensMertelmeyer** [comment]
The store gifted me with version `2021.805.2229.0` and the ListView is working flawlessly now for me. 👍
